platform :ios, '8.0'

target 'HBMVVMProject' do
# pod 'SDWebImage', '~> 3.8.0'
 #pod 'SDWebImage-Category', '~> 1.4'
 #pod 'SDWebImage-CircularProgressView', '~> 0.1.1'
# pod 'SDWebImageGifWithFLAnimatedImageDemo', '~> 1.0.0'
 pod 'SDWebImageWebPCoder', '~> 0.2.3'
 pod 'SDWebImageYYPlugin', '~> 0.2.1'
 #pod 'ZYImageDownloader', '~> 0.1.0'
 pod 'AFNetworking'
 pod 'Masonry', '~> 1.1.0'
 pod 'ReactiveObjC'
 pod 'SDRouter', '~> 1.0.0'
 pod 'JLRoutes', '~> 2.1'
 pod 'YYModel'
 pod 'YYCache'
 pod 'YYImage'
 pod 'YYWebImage'
 pod 'YYText'
 pod 'YYKeyboardManager'
pod 'YYDispatchQueuePool'
pod 'YYAsyncLayer'
pod 'YYCategories'
#pod 'AsyncDisplayKit'
pod 'OpenCV'
end
